# Generated by Django 3.0 on 2021-05-13 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubscribersInventory', '0004_auto_20210511_1557'),
        ('Billing', '0006_auto_20210512_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlycharge',
            name='client_full_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubscribersInventory.VoIpInformation'),
        ),
    ]
