# Generated by Django 3.0 on 2021-05-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0020_auto_20210517_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlycharge',
            name='client_full_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
