# Generated by Django 3.2 on 2021-05-04 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_request_date', models.DateField(blank=True, null=True)),
                ('request_date_initiated', models.DateField(blank=True, null=True)),
                ('date_line_activated', models.DateField(blank=True, null=True)),
                ('date_line_terminated', models.DateField(blank=True, null=True)),
                ('phone_line_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], max_length=100)),
                ('client_company_user', models.CharField(blank=True, choices=[('Vodaconnect', 'Vodaconnect'), ('Landmaster.Us', 'Landmaster.Us'), ('CallMe.Com.Ph', 'CallMe.Com.Ph'), ('PsalmsGlobal.Com', 'PsalmsGlobal.Com')], max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Activation Details',
                'verbose_name_plural': 'Activation Details',
                'ordering': ['client_company_user'],
            },
        ),
        migrations.CreateModel(
            name='ForwardingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forwarding_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='Forwarding Number: (Customer Phone Line)')),
            ],
            options={
                'verbose_name': 'Forwarding Information',
                'verbose_name_plural': 'Forwarding Information',
                'ordering': ['forwarding_num'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_logins', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_types', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriberStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_production', models.CharField(choices=[('New Prospect', 'New Prospect'), ('New Request', 'New Request'), ('Pending Request', 'Pending Request'), ('Call/Email Follow up', 'Call/Email Follow up'), ('Ready to Start', 'Ready to Start'), ('Sign up - Ready for Set up', 'PendSign up - Ready for Set uping'), ('Active - Live in Production', 'Active - Live in Production'), ('Request for Cancellation', 'Request for Cancellation'), ('Email sent for Cancellation', 'Email sent for Cancellation'), ('Account Cancelled by Vodaconnect', 'Account Cancelled by Vodaconnect'), ('Recurring Charge Cancelled', 'Recurring Charge Cancelled'), ('Account Cancelled', 'Account Cancelled')], max_length=100, verbose_name='Status In Production')),
                ('type_of_request', models.CharField(choices=[('New Number Request', 'New Number Request'), ('Porting Request', 'Porting Request'), ('Other Request', 'Other Request')], max_length=100, verbose_name='Type of Request ')),
                ('ready_for_testimony', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Applicable', 'Not Applicable')], max_length=100, verbose_name='Ready For Testimony?')),
            ],
            options={
                'verbose_name': 'Subscriber Status',
                'verbose_name_plural': 'Subscriber Status',
                'ordering': ['stat_production'],
            },
        ),
        migrations.CreateModel(
            name='VodaConnectNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vodaconnect_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZiptrunkLoginDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ziptrunk_logins', models.CharField(blank=True, max_length=100, null=True)),
                ('ziptrunk_details', models.TextField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VOIPInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_full_name', models.CharField(blank=True, max_length=500, null=True)),
                ('client_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.clientcode')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
                ('vodaconnect_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubscribersInventory.vodaconnectnumber')),
            ],
            options={
                'verbose_name': 'VOIP Information',
                'verbose_name_plural': 'VOIP Information',
                'ordering': ['client_full_name'],
            },
        ),
        migrations.CreateModel(
            name='TotalNumExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension_logins', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('extension_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubscribersInventory.forwardinginfo', verbose_name='Extension Number')),
            ],
        ),
        migrations.CreateModel(
            name='PlanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Total Cost')),
                ('recurring_bill', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], max_length=100, verbose_name='Did we set up recurring bill?')),
                ('pypal_bill', models.TextField(blank=True, null=True, verbose_name='Paypal Details for Billing')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('plan_types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubscribersInventory.plantype')),
            ],
            options={
                'verbose_name': 'Plan Details',
                'verbose_name_plural': 'Plan Details',
                'ordering': ['pypal_bill'],
            },
        ),
    ]
