# Generated by Django 3.0 on 2021-05-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubscribersInventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voipinformation',
            options={'ordering': ['client_full_name'], 'verbose_name': 'VoIpInformation', 'verbose_name_plural': 'VoIpInformation'},
        ),
        migrations.AlterField(
            model_name='voipinformation',
            name='company_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
