# Generated by Django 3.0 on 2021-05-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubscribersInventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalnumextension',
            name='extension_num',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Extension Number'),
        ),
    ]
