# Generated by Django 3.0 on 2021-05-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubscribersInventory', '0002_auto_20210507_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationdetail',
            name='date_line_activated',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='activationdetail',
            name='date_line_terminated',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='activationdetail',
            name='order_request_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='activationdetail',
            name='request_date_initiated',
            field=models.DateField(null=True),
        ),
    ]
