# Generated by Django 3.0 on 2021-05-21 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='pin',
            new_name='create_pin',
        ),
    ]
