# Generated by Django 3.0 on 2021-05-12 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_client_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='profile_picture',
        ),
    ]
