# Generated by Django 3.0 on 2021-05-21 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210521_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='create_pin',
            new_name='pin',
        ),
    ]
