# Generated by Django 3.0 on 2021-05-26 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210521_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpersonalfile',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.ClientCode'),
        ),
    ]
