# Generated by Django 3.0 on 2021-05-12 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_client_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='profile_pic',
        ),
    ]
