# Generated by Django 3.0 on 2021-05-19 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SubscribersInventory', '__first__'),
        ('authentication', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('file_description', models.TextField(blank=True, null=True)),
                ('client_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.ClientCode')),
                ('client_full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubscribersInventory.VoIpInformation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
