# Generated by Django 3.2 on 2021-05-04 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '__first__'),
        ('SubscribersInventory', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('file_description', models.TextField(blank=True, null=True)),
                ('client_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.clientcode')),
                ('client_full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubscribersInventory.voipinformation')),
            ],
        ),
    ]
