# Generated by Django 3.0 on 2021-05-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountFiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountfile',
            name='client_full_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
