# Generated by Django 3.0 on 2021-05-12 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubscribersInventory', '0004_auto_20210511_1557'),
        ('AccountFiles', '0002_auto_20210511_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountfile',
            name='client_full_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubscribersInventory.VoIpInformation'),
        ),
    ]
