# Generated by Django 3.0 on 2021-05-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderRequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='company_name',
            field=models.CharField(blank=True, choices=[('Vodaconnect', 'Vodaconnect'), ('G.P.G Corporation', 'G.P.G Corporation'), ('Landmaster.Us', 'Landmaster.Us'), ('CallMe.Com.Ph', 'CallMe.Com.Ph'), ('PsalmsGlobal.Com', 'PsalmsGlobal.Com'), ('Affiliate Partner', 'Affiliate Partner')], max_length=150, null=True, verbose_name='Company Name ( That will appear in your caller ID)'),
        ),
    ]
