# Generated by Django 3.0 on 2021-05-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderRequest', '0003_auto_20210514_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='total Number Of Phone Lines Needed'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='preferred_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Prepared Area Code'),
        ),
    ]
