# Generated by Django 3.0 on 2021-05-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderRequest', '0004_auto_20210514_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='preferred_code',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Prepared Area Code'),
        ),
    ]
